services:

  front: 
    image: luisberrio13/sic-frontend:3.0
    hostname: frontend
    ports:
      - "4000:4000"
    networks:
      - sic-network
    depends_on:
      - api-gateway
  
  api-gateway:
    image: luisberrio13/api-gateway-1
    hostname: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - process-service
      - document-service
    networks:
      - sic-network

  user-service:
    image: luisberrio13/user-service
    hostname: user-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - mysql
    networks:
      - sic-network

  process-service:
    image: luisberrio13/process-service
    hostname: process-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/processdb
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - mysql
    networks:
      - sic-network

  document-service:
      image: luisberrio13/document-service
      hostname: documents-service
      ports:
        - "8081:8081"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/documentdb
        - SPRING_DATASOURCE_USERNAME=root
      depends_on:
        - mysql
      networks:
        - sic-network

  mysql:
    image: luisberrio13/mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - sic-network
    restart: always

networks:
  sic-network:
    driver: bridge
